### ISSUE TITLE
Add /minting command showing minting so far excluding current minting period

### ISSUE THREAD

**Issue by mik-tf** [threefoldfoundation/node-status-bot#9]
# Features Request

- Add /minting command showing minting so far excluding current minting period

# Details

- Currently the Dashboard allows farmers to download the minting receipt in PDF
- Then they can see minting so far for the whole farm, and each node

# Todo

- Can we add a command /minting on the node status bot showing the minted TFT so far?

**Comment by scottyeager** [comment]
https://github.com/threefoldfoundation/peppermint
